// D1 path rewriter: performs "dual-base probing absolutization" on relative-path
// references inside the local-skill index-instruction text injected into the Agent context.
//
// Design source: .workbuddy/memory/local-skill-import-design.md §2.5.
// Coverage (declaration narrowed, Review #3 Route A): applies ONLY to the
// "index-instruction text injected into the Agent context"
// (i.e. the index card generated by buildLocalImportedInstructions + the
// buildLocalExecutionBoundary soft hint, see composeLocalSkillPrompt in
// request-augmentation.ts). The thisFileDir/skillDir/fileExists of these texts
// are known at augment time (from the skill registration's includedFiles/
// scriptFiles/omittedFiles manifest).
//
// Not covered: the local skill's real SKILL.md body and its reference file
// contents — those are read on demand by the Agent after activation via
// local_file_read into the continuation context; this function is NOT called at
// that read boundary (see "Plan 2 index shape" in local-importer.ts:
// buildLocalImportedInstructions). Relative references inside the real body
// rely on the Agent following the "double-base rule" in the D4 soft hint to
// resolve themselves; this layer does not force-rewrite them, to avoid
// corrupting examples / code blocks / dynamically generated paths.
//
// Algorithm (dual-base probing, only for index-instruction text):
//   1) first join(thisFileDir, rel), use if fileExists;
//   2) else join(skillDir, rel), use if fileExists;
//   3) neither exists -> keep as-is (no harm to URL / absolute path / placeholder / `..` escape).
// Escape check: if rel escapes the skillDir root via joinUnderRoot -> do not rewrite (anti-escape).
//
// Browser constraint: this module uses only pure-string path helpers, not
// node:path (the extension is bundled for the browser environment).
// Note: this module is the canonical algorithm implementation of D1. Under the
// "Agent-driven, on-demand local_file_read loading" model, the real disk read
// and recursive loading are done by the Agent; this function acts as a
// defensive/normalizing measure, absolutizing only the injected index-instruction
// text, mirrored by the Agent instruction (see buildLocalExecutionBoundary).
// References inside code blocks (fenced ``` / ~~~ and inline `) are treated as
// examples and skipped.

const SEP_RE = /[\\/]+/;
const URL_RE = /^[a-z][a-z0-9+.-]*:\/\//i;

export function isAbsolutePath(p: string): boolean {
  if (/^[a-zA-Z]:[\\/]/.test(p)) return true; // Windows drive letter
  return p.startsWith('/') || p.startsWith('\\');
}

function splitParts(p: string): string[] {
  return p.split(SEP_RE).filter(Boolean);
}

// Resolve rel under root; if rel escapes the filesystem root via `..` (out empty), return null (out-of-bounds).
export function joinUnderRoot(root: string, rel: string): string | null {
  const rootParts = splitParts(root);
  const relParts = splitParts(rel);
  const out: string[] = [...rootParts];
  for (const part of relParts) {
    if (part === '.') continue;
    if (part === '..') {
      if (out.length === 0) return null;
      out.pop();
    } else {
      out.push(part);
    }
  }
  const sep = /[\\/]/.test(root) && root.includes('\\') ? '\\' : '/';
  let result = out.join(sep);
  // Preserve the root's leading separator so an absolute root (e.g. /skills/demo) stays absolute after resolution (/skills/...).
  if ((root.startsWith('/') || root.startsWith('\\')) && !result.startsWith(sep)) {
    result = sep + result;
  }
  return result;
}

// Determine whether absPath is still inside root (inclusive of equal-to-root).
// absPath must first be resolved by joinUnderRoot into a root-based absolute path.
// Purpose: the "anti-escape" guard of absolutizeSkillReferences — a relative ref
// that escapes the skillDir root via `..` (e.g. /skills/demo -> /skills/etc) is
// treated as out-of-bounds and not rewritten. Note: joinUnderRoot===null alone
// only catches escaping the "filesystem root", not escaping into a sibling of
// root, hence this containment check is required.
function isUnderRoot(root: string, absPath: string): boolean {
  const rootParts = splitParts(root);
  const pathParts = splitParts(absPath);
  if (pathParts.length < rootParts.length) return false;
  for (let i = 0; i < rootParts.length; i++) {
    if (pathParts[i] !== rootParts[i]) return false;
  }
  return true;
}

const MARKDOWN_REF_RE = /(\]\()([^)\s]+)(\))/g;

// Code segments (fenced ``` / ~~~ and inline `): their [link](path) are mostly
// examples and should NOT be absolutized. Extract them first with a private-zone
// placeholder for protection, rewrite the non-code region, then restore, to
// avoid polluting the displayed text.
const CODE_SEGMENT_RE = /(?:```|~~~)[\s\S]*?(?:```|~~~)|`[^`\n]*`/g;
const CODE_OPEN = '';
const CODE_CLOSE = '';

export interface LocalPathRewriteOptions {
  skillDir: string;
  thisFileDir: string;
  fileExists: (absolutePath: string) => boolean;
}

export function absolutizeSkillReferences(text: string, options: LocalPathRewriteOptions): string {
  const { skillDir, thisFileDir, fileExists } = options;
  // Extract code segments to protect them from being rewritten.
  const codeSegments: string[] = [];
  const protectedText = text.replace(CODE_SEGMENT_RE, (segment) => {
    const index = codeSegments.push(segment) - 1;
    return `${CODE_OPEN}${index}${CODE_CLOSE}`;
  });
  const rewritten = protectedText.replace(MARKDOWN_REF_RE, (match, open: string, rawPath: string, close: string) => {
    const trimmed = rawPath.trim();
    if (!trimmed) return match;
    if (URL_RE.test(trimmed)) return match; // URL
    if (trimmed.startsWith('#')) return match; // anchor
    if (isAbsolutePath(trimmed)) return match; // already absolute
    if (trimmed.startsWith('~')) return match; // home dir placeholder
    // Escape check: if rel escapes the skillDir root (not inside root) via `..` -> do not rewrite (anti-escape).
    const candidateUnderSkill = joinUnderRoot(skillDir, trimmed);
    if (candidateUnderSkill === null) return match;
    if (!isUnderRoot(skillDir, candidateUnderSkill)) return match;

    const base1 = joinUnderRoot(thisFileDir, trimmed);
    if (base1 && fileExists(base1)) return `${open}${base1}${close}`;
    const base2 = joinUnderRoot(skillDir, trimmed);
    if (base2 && fileExists(base2)) return `${open}${base2}${close}`;
    return match; // neither exists: keep as-is (no harm)
  });
  // Restore code segments (fixed placeholder format, no nesting risk).
  return rewritten.replace(new RegExp(`${CODE_OPEN}(\\d+)${CODE_CLOSE}`, 'g'), (_m, index: string) => codeSegments[Number(index)]);
}
